# Generated by Django 4.2.11 on 2024-04-28 19:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_options_alter_contactformentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformentry',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
